spring:
  application:
    name: test-consumer
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  sleuth:
    enabled: false
    http:
      legacy:
        enabled: true
  zipkin:
    enabled: false
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        metadata:
          h.version: v0.0.1
    sentinel:
      transport:
        dashboard: 192.168.50.80:8887
        port: 20022
      eager: true

server:
  port: 10022

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    ebabled: true

logging:
  file:
    name: log/${spring.application.name}.log
  pattern:
    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
